config/routes.rb
Hearthstone::Application.routes.draw do
  get "welcome/index"
  root to:'welcome#index'

  post 'data_loader/upload' => 'data_loader#upload'
  resources :cards
  devise_for :users
  resources :data_loader, :only => [:index, :upload]

  resources :users do
    get 'stat_entries/overview' => 'stat_entries#overview'
    post 'stat_entries/select_overview' => 'stat_entries#select_overview'
    resources :stat_entries
    resources :decks do
      get 'add_cards/add_card/:card_id' => 'add_cards#add_card', :as => :add_card
      delete 'add_cards/remove_card/:card_id' => 'add_cards#remove_card', :as => :remove_card
      resources :add_cards do

      end
    end
  end

  

end

app/models/stat_entry.rb
# == Schema Information
#
# Table name: stat_entries
#
#  id         :integer          not null, primary key
#  hero       :string(255)
#  opp_hero   :string(255)
#  game_mode  :string(255)
#  result     :string(255)
#  first      :boolean
#  created_at :datetime
#  updated_at :datetime
#  user_id    :integer
#

class StatEntry < ActiveRecord::Base
	belongs_to :user
end

app/controllers/stat_entries_controller.rb
class StatEntriesController < ApplicationController

	helper_method :sort_column, :sort_direction

	def new
		# create new instance of StatEntry
		@stat_entry = StatEntry.new
		# get the permission
		authorize! :new, @stat_entry
	end

	def create
		# find the User object with the corresponding id
		@user = User.find(params[:user_id])
		# create a new StatEntry for the user
		@stat_entry = @user.stat_entries.create(params[:stat_entry].permit(:hero, :opp_hero, :game_mode, :result, :first))
		# get the permission
		authorize! :create, @stat_entry 

		# store the object
		if @stat_entry.save
			redirect_to user_stat_entries_path
		else
			render 'new'
		end
	end

	def edit
		# find the User object with the corresponding id
		@user = User.find(params[:user_id])
		# find the StatEntry object with the corresponding id of the user
		@stat_entry = @user.stat_entries.find(params[:id])
		# get the permisson
		authorize! :update, @stat_entry 
	end

	def show
		# find the User object with the corresponding id
		@user = User.find(params[:user_id])
		# find the StatEntry object with the corresponding id of the user
		@stat_entry = @user.stat_entries.find(params[:id])
		# get the permisson
		authorize! :read, @stat_entry
	end

	def index
		# find the User object with the corresponding id
		@user = User.find(params[:user_id])
		# get all the entries of a user in a sorted order
		@stat_entries  = @user.stat_entries.order(sort_column + ' ' + sort_direction)		
		# get the permission
		authorize! :read, @stat_entries
	end

	def destroy
		# find the User object with the corresponding id
		@user = User.find(params[:user_id])
		# find the StatEntry object with the corresponding id of the user
	  @stat_entry = @user.stat_entries.find(params[:id])
		# get the permission
		authorize! :delete, @stat_entry
		# destroy it
	  @stat_entry.destroy
 
		# show all stats
	  redirect_to user_stat_entries_path
	end

	def update
		# find the StatEntry object with the corresponding id
		@stat_entry = StatEntry.find(params[:id])
		# get the permission
		authorize! :update, @stat_entry
	 
		# update it
		if @stat_entry.update(params[:stat_entry].permit(:hero, :opp_hero, :game_mode, :result, :first))
			# show all stats
		  redirect_to user_stat_entries_path
		else
		  render 'edit'
		end
	end

	def overview
		# create new instance of StatEntry
		@stat_entry = StatEntry.new
		# get the permission
		authorize! :new, @stat_entry
	end

	def select_overview
		# find the User object with the corresponding id
		@user = User.find(params[:user_id])
		# do the query to select the desired stat entries
		if params[:stat_entry].permit([:first])[:first] == "All"
			@stat_entries = @user.stat_entries.where("(hero = :hero OR (:hero = 'All')) AND (opp_hero = :opp_hero OR (:opp_hero = 'All'))
			AND (game_mode = :game_mode OR (:game_mode = 'All'))",
			{hero: params[:stat_entry].permit([:hero])[:hero],
			opp_hero: params[:stat_entry].permit([:opp_hero])[:opp_hero],
			game_mode: params[:stat_entry].permit([:game_mode])[:game_mode]}).order('created_at DESC')
		else
			@stat_entries = @user.stat_entries.where("(hero = :hero OR (:hero = 'All')) AND (opp_hero = :opp_hero OR (:opp_hero = 'All'))
			AND (game_mode = :game_mode OR (:game_mode = 'All'))
			AND first = :first",
			{hero: params[:stat_entry].permit([:hero])[:hero],
			opp_hero: params[:stat_entry].permit([:opp_hero])[:opp_hero],
			game_mode: params[:stat_entry].permit([:game_mode])[:game_mode],
			first: params[:stat_entry].permit([:first])[:first]}).order('created_at DESC')
		end

		# count the number of wins/losses
		@nbr_win = @stat_entries.where(result: 'Victory').count
		@nbr_loss = @stat_entries.where(result: 'Defeat').count
	end

	# helper functions for sorting
  private
  def sort_column
    StatEntry.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end
end

app/helpers/stat_entries_helper.rb
module StatEntriesHelper
end

app/views/stat_entries/edit.html.erb
<h1>Edit Stat Entry</h1>

<%= form_for @stat_entry, url: {action: "update"}, :html => { :class => 'form-horizontal' }  do |f| %>
  <div class="control-group">
    <%= f.label :hero, :class => 'control-label' %>
		<div class="controls">
    	<%= f.select :hero, [['Priest'], ['Warrior'], ['Warlock'], ['Mage'], ['Druid'], ['Hunter'], ['Shaman'], ['Paladin'], ['Rogue']] %>
		</div>
  </div>
 
  <div class="control-group">
    <%= f.label :opp_hero, :class => 'control-label' %>
		<div class="controls">
    	<%= f.select :opp_hero, [['Priest'], ['Warrior'], ['Warlock'], ['Mage'], ['Druid'], ['Hunter'], ['Shaman'], ['Paladin'], ['Rogue']] %>
		</div>
  </div>
 
  <div class="control-group">
    <%= f.label :game_mode, :class => 'control-label' %>
		<div class="controls">
    	<%= f.select :game_mode, [['Practice'], ['Play'], ['The Arena']] %>
		</div>
  </div>

  <div class="control-group">
    <%= f.label :result, :class => 'control-label' %>
		<div class="controls">
    	<%= f.select :result, [['Victory'], ['Defeat']] %>
		</div>
  </div>

  <div class="control-group">
    <%= f.label :first, :class => 'control-label' %>
		<div class="controls">
    	<%= f.select :first, [['Yes', true], ['No', false]] %>
		</div>
  </div>

   <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                user_stat_entries_path, :class => 'btn' %>
  </div>
<% end %>

app/views/stat_entries/index.html.erb
<%- model_class = StatEntry -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= sortable "id","Id" %></th>
      <th><%= sortable "hero","Hero" %></th>
      <th><%= sortable "opp_hero","Opponent Hero" %></th>
      <th><%= sortable "game_mode","Game Mode" %></th>
      <th><%= sortable "result","Result" %></th>
      <th><%= sortable "first","Did you go first?" %></th>
      <th><%= sortable "created_at","Created at" %></th>
      <th><%= sortable "updated_at","Updated at" %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @stat_entries.each do |stat_entry| %>
      <tr>
        <td><%= link_to stat_entry.id, user_stat_entry_path(stat_entry.user_id, stat_entry) %></td>
        <td><%= stat_entry.hero %></td>
        <td><%= stat_entry.opp_hero %></td>
        <td><%= stat_entry.game_mode %></td>
        <td><%= stat_entry.result %></td>
				<% if stat_entry.first %>
		    	<td>Yes</td>
				<% else %>
					<td>No</td>
				<% end %>
        <td><%= stat_entry.created_at %></td>
        <td><%= stat_entry.updated_at %></td>
        <td>
          <%= link_to t('.update', :default => t("helpers.links.edit")),
                      edit_user_stat_entry_path(stat_entry.user_id,stat_entry), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_stat_entry_path(stat_entry.user_id,stat_entry),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_stat_entry_path,
            :class => 'btn btn-primary' %>

app/views/stat_entries/new.html.erb
<h1>Create Stat Entry</h1>

<%= form_for @stat_entry, url: {action: "create"}, :html => { :class => 'form-horizontal' }  do |f| %>
  <div class="control-group">
    <%= f.label :hero, :class => 'control-label' %>
		<div class="controls">
    	<%= f.select :hero, [['Priest'], ['Warrior'], ['Warlock'], ['Mage'], ['Druid'], ['Hunter'], ['Shaman'], ['Paladin'], ['Rogue']] %>
		</div>
  </div>
 
  <div class="control-group">
    <%= f.label :opp_hero, :class => 'control-label' %>
		<div class="controls">
    	<%= f.select :opp_hero, [['Priest'], ['Warrior'], ['Warlock'], ['Mage'], ['Druid'], ['Hunter'], ['Shaman'], ['Paladin'], ['Rogue']] %>
		</div>
  </div>
 
  <div class="control-group">
    <%= f.label :game_mode, :class => 'control-label' %>
		<div class="controls">
    	<%= f.select :game_mode, [['Practice'], ['Play'], ['The Arena']] %>
		</div>
  </div>

  <div class="control-group">
    <%= f.label :result, :class => 'control-label' %>
		<div class="controls">
    	<%= f.select :result, [['Victory'], ['Defeat']] %>
		</div>
  </div>

  <div class="control-group">
    <%= f.label :first, :class => 'control-label' %>
		<div class="controls">
    	<%= f.select :first, [['Yes', true], ['No', false]] %>
		</div>
  </div>

   <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                user_stat_entries_path, :class => 'btn' %>
  </div>
<% end %>

app/views/stat_entries/overview.html.erb
<h1>Stat Entries Overview</h1>

<%= form_for @stat_entry, url: {action: "select_overview"}, :html => { :class => 'form-horizontal' }  do |f| %>
  <div class="control-group">
    <%= f.label :hero, :class => 'control-label' %>
		<div class="controls">
    	<%= f.select :hero, [['All', 'All'], ['Priest'], ['Warrior'], ['Warlock'], ['Mage'], ['Druid'], ['Hunter'], ['Shaman'], ['Paladin'], ['Rogue']] %>
		</div>
  </div>
 
  <div class="control-group">
    <%= f.label :opp_hero, :class => 'control-label' %>
		<div class="controls">
    	<%= f.select :opp_hero, [['All', 'All'], ['Priest'], ['Warrior'], ['Warlock'], ['Mage'], ['Druid'], ['Hunter'], ['Shaman'], ['Paladin'], ['Rogue']] %>
		</div>
  </div>
 
  <div class="control-group">
    <%= f.label :game_mode, :class => 'control-label' %>
		<div class="controls">
    	<%= f.select :game_mode, [['All', 'All'], ['Practice'], ['Play'], ['The Arena']] %>
		</div>
  </div>

  <div class="control-group">
    <%= f.label :first, :class => 'control-label' %>
		<div class="controls">
    	<%= f.select :first, [['All', 'All'], ['Yes', true], ['No', false]] %>
		</div>
  </div>

   <div class="form-actions">
    <%= f.submit 'Show', :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                user_stat_entries_path, :class => 'btn' %>
  </div>
<% end %>

app/views/stat_entries/select_overview.html.erb
<%- model_class = StatEntry -%>

<script type="text/javascript">
	$(function () {
		    var chart = new Highcharts.Chart({
		      chart: {
		        renderTo: 'chart',
		        type: 'pie'
		      },
					title: {
						text: 'Game Statistics'        
					},
          tooltip: {
      	    pointFormat: '<b>{point.percentage:.1f}%</b>'
          },
		      plotOptions: {
		        pie: {
		          allowPointSelect: true,
		          slicedOffset: 0,
		          states: {
	              select: {
	                color: '#666'
	          	  }
		        	},
							showInLegend: true
		      	}
		  		},

				  series: [{
			      data: [['Victory', <%= @nbr_win %>], ['Defeat', <%= @nbr_loss %>]]        
				  }]
			  });
	});
</script>

<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<h2>Chart</h2>
<div id="chart" style="width:300px; height:300px; margin-left:auto; margin-right:auto;"></div>

<h2>Results</h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Id</th>
      <th>Hero</th>
      <th>Opponent Hero</th>
      <th>Game Mode</th>
      <th>Result</th>
      <th>Did you go first?</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @stat_entries.each do |stat_entry| %>
      <tr>
        <td><%= link_to stat_entry.id, user_stat_entry_path(stat_entry.user_id, stat_entry) %></td>
        <td><%= stat_entry.hero %></td>
        <td><%= stat_entry.opp_hero %></td>
        <td><%= stat_entry.game_mode %></td>
        <td><%= stat_entry.result %></td>
				<% if stat_entry.first %>
		    	<td>Yes</td>
				<% else %>
					<td>No</td>
				<% end %>
        <td><%= stat_entry.created_at %></td>
        <td><%= stat_entry.updated_at %></td>
        <td>
          <%= link_to t('.update', :default => t("helpers.links.edit")),
                      edit_user_stat_entry_path(stat_entry.user_id,stat_entry), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_stat_entry_path(stat_entry.user_id,stat_entry),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/stat_entries/show.html.erb
<%- model_class = StatEntry -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Id</th>
      <th>Hero</th>
      <th>Opponent Hero</th>
      <th>Game Mode</th>
      <th>Result</th>
      <th>Did you go first?</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= link_to @stat_entry.id, user_stat_entry_path(@stat_entry.user_id, @stat_entry) %></td>
      <td><%= @stat_entry.hero %></td>
      <td><%= @stat_entry.opp_hero %></td>
      <td><%= @stat_entry.game_mode %></td>
      <td><%= @stat_entry.result %></td>
			<% if @stat_entry.first %>
      	<td>Yes</td>
			<% else %>
				<td>No</td>
			<% end %>
      <td><%= @stat_entry.created_at %></td>
      <td><%= @stat_entry.updated_at %></td>
      <td>
        <%= link_to t('.update', :default => t("helpers.links.edit")),
                    edit_user_stat_entry_path(@stat_entry.user_id,@stat_entry), :class => 'btn btn-mini' %>
        <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                    user_stat_entry_path(@stat_entry.user_id,@stat_entry),
                    :method => :delete,
                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                    :class => 'btn btn-mini btn-danger' %>
      </td>
    </tr>
  </tbody>
</table>

<%= link_to t('.back', :default => t("helpers.links.back")),
            user_stat_entries_path(@stat_entry.user_id),
            :class => 'btn btn-primary' %>