config/routes.rb
Hearthstone::Application.routes.draw do
  get "welcome/index"
  root to:'welcome#index'

  post 'data_loader/upload' => 'data_loader#upload'
  resources :cards
  devise_for :users
  resources :data_loader, :only => [:index, :upload]

  resources :users do
    get 'stat_entries/overview' => 'stat_entries#overview'
    post 'stat_entries/select_overview' => 'stat_entries#select_overview'
    resources :stat_entries
    resources :decks do
      get 'add_cards/add_card/:card_id' => 'add_cards#add_card', :as => :add_card
      delete 'add_cards/remove_card/:card_id' => 'add_cards#remove_card', :as => :remove_card
      resources :add_cards do

      end
    end
  end

  

end

app/controllers/add_cards_controller.rb
# encoding: utf-8
class AddCardsController < ApplicationController
  helper_method :sort_column, :sort_direction

  #lists the current deck and all available cards
  #calculates the current number of cards in the deck
  def index
    @user = User.find(params[:user_id])
    @deck = Deck.find(params[:deck_id])
    @cards = Card.where('card_class = ? OR card_class = ?', @deck.deck_type, 'Neutral').search(params[:search]).order(sort_column+' '+sort_direction).paginate(:per_page => 14, :page => params[:page])
    #@currentNumberOfCards = @deck.card_decks.where(deck: @deck).sum("quantity")
    @currentNumberOfCards = @deck.current_number_of_cards
  end

  #adds a card to the current deck
  def add_card
    @user = User.find(params[:user_id])
    @deck = Deck.find(params[:deck_id])
    @card = Card.find(params[:card_id])
    authorize! :edit, @deck

    @currentNumberOfCards = @deck.card_decks.where(deck: @deck).sum("quantity")
    if @currentNumberOfCards >= 30
      flash[:alert]="You cannot have more than 30 cards in your deck"
    else
      if @deck.cards.include?(@card)
        if @deck.card_decks.where(card: @card, deck: @deck).sum("quantity") >= 2
          flash[:alert]='You already have two ' + @card.name.pluralize() + ' in your deck!'
        else
          card_deck = @deck.card_decks.where(card: @card, deck: @deck).take!
          card_deck.quantity = 2
          card_deck.save
        end
      else
        @deck.cards << @card
        cardDeck = @deck.card_decks.where(card: @card, deck: @deck).take!
        cardDeck.quantity = 1
        cardDeck.save
      end
    end
    redirect_to user_deck_add_cards_path(@user.id.to_s, @deck.id.to_s)
  end


  def remove_card
    @deck = Deck.find(params[:deck_id])
    @card = Card.find(params[:card_id])
    @user = User.find(params[:user_id])
    authorize! :edit, @deck
    cardDeck = @deck.card_decks.where(card: @card, deck: @deck).take!
    if @deck.cards.include?(@card) && cardDeck.quantity==2
      cardDeck.quantity = 1
      cardDeck.save
    else
      @deck.cards.destroy(@card)
    end
    redirect_to user_deck_add_cards_path(@user.id.to_s, @deck.id.to_s)
  end

  private
# Use callbacks to share common setup or constraints between actions.
  def sort_column
    Card.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/helpers/add_cards_helper.rb
module AddCardsHelper
end

app/views/add_cards/_cards.html.erb
<%- model_class = Deck -%>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= sortable "name", model_class.human_attribute_name(:name) %></th>
    <th><%= sortable "card_class","Class" %></th>
    <th><%= sortable "rarity", model_class.human_attribute_name(:rarity) %></th>
    <th><%= sortable "cost", model_class.human_attribute_name(:cost) %></th>
    <th><%= sortable "attack", model_class.human_attribute_name(:attack) %></th>
    <th><%= sortable "health", model_class.human_attribute_name(:health) %></th>
    <th><%=t '.actions', :default => t("helpers.actions") %></th>
  </tr>
  </thead>
  <tbody>
  <% @cards.each do |card| %>
      <tr>
        <td><%= card.name %></td>
        <td><%= card.card_class %></td>
        <td><%= card.rarity %></td>
        <td><%= card.cost %></td>
        <td><%= card.attack %></td>
        <td><%= card.health %></td>
        <td>
          <%= link_to image_tag("/images/add.png"), user_deck_add_card_path(@user.id, @deck, card)%>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate @cards %>

app/views/add_cards/index.html.erb
<%- model_class = Deck -%>
<div>
  <div style="width:49%; float: left; margin-right: 2%;">
    <h1>Available Cards</h1>
    <%= form_tag user_deck_add_cards_path(@user.id.to_s,@deck.id.to_s), :method => 'get', :id => "cards_search" do  %>
        <%= hidden_field_tag :direction, params[:direction] %>
        <%= hidden_field_tag :sort, params[:sort] %>
        <p>
          <%= text_field_tag :search, params[:search] %>
          <%= submit_tag "Search", :name => nil %>
        </p>
    <% end %>
    <div id="available_cards"><%= render 'cards'%></div>

  </div>
  <div style="width:49%; float: left;">
    <h1>Cards in this deck (<%= @currentNumberOfCards.to_s %>/30)</h1>
    <table class="table table-striped">
      <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:name) %></th>
        <th><%= model_class.human_attribute_name(:rarity) %></th>
        <th><%= model_class.human_attribute_name(:cost) %></th>
        <th><%= model_class.human_attribute_name(:attack) %></th>
        <th><%= model_class.human_attribute_name(:health) %></th>
        <th><%= model_class.human_attribute_name(:quantity) %></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
      </thead>
      <tbody>
      <%
         @deck.card_decks.each do |cardDeck|
           card = Card.find(cardDeck.card_id)
      %>

          <tr>
            <td><%= card.name %></td>
            <td><%= card.rarity %></td>
            <td><%= card.cost %></td>
            <td><%= card.attack %></td>
            <td><%= card.health %></td>
            <td><%= cardDeck.quantity %> </td>
            <td>
              <%= link_to image_tag("/images/delete.png"), user_deck_remove_card_path(@user.id,@deck,card), :method => 'delete' %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <div style="clear: both;"></div>
</div>

app/views/add_cards/index.js.erb
$('#available_cards').html('<%= escape_javascript(render('cards')) %>');