config/routes.rb
Hearthstone::Application.routes.draw do
  get "welcome/index"
  root to:'welcome#index'

  post 'data_loader/upload' => 'data_loader#upload'
  resources :cards
  devise_for :users
  resources :data_loader, :only => [:index, :upload]

  resources :users do
    get 'stat_entries/overview' => 'stat_entries#overview'
    post 'stat_entries/select_overview' => 'stat_entries#select_overview'
    resources :stat_entries
    resources :decks do
      get 'add_cards/add_card/:card_id' => 'add_cards#add_card', :as => :add_card
      delete 'add_cards/remove_card/:card_id' => 'add_cards#remove_card', :as => :remove_card
      resources :add_cards do

      end
    end
  end

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Hearthstone" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application", "highcharts" %>
    <%= auto_discovery_link_tag(:atom, cards_path(format: "atom")) %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Hearthstone</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li data-no-turbolink><%= link_to "Card Manager", cards_path  %></li>
              <% if user_signed_in? %>
				<li id="fat-menu" class="dropdown">
                	<a href="#" class="dropdown-toggle" data-toggle="dropdown">Statistics<b class="caret"></b> </a>
                  <ul class="dropdown-menu">
                    <li> <%= link_to "Add", new_user_stat_entry_path(current_user.id) %></li>
                    <li class="divider"></li>
                    <li><%= link_to "Show all", user_stat_entries_path(current_user.id) %></li>
                    <li class="divider"></li>
                    <li><%= link_to "Overview", user_stat_entries_overview_path(current_user.id) %> </li>
                  </ul>
                </li>
                  <li id="fat-menu2" class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Decks<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                      <li> <%= link_to "Add", new_user_deck_path(current_user.id) %> </li>
                      <li class="divider"></li>
                      <li> <%= link_to "Show all", user_decks_path(current_user.id)%></li>
                    </ul>
                  </li>
				<% end %>
            </ul>
            <ul class="nav pull-right">
              <% if user_signed_in? %>
                  <li id="fat-menu" class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      My Account<b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><%= link_to "Settings", edit_user_registration_path %></li>
                      <li class="divider"></li>
                      <li>
                        <%= link_to "Sign out", destroy_user_session_path, method: "delete" %>
                      </li>
                    </ul>
                  </li>
              <% else %>
                  <li><%= link_to "Sign up", new_user_registration_path  %></li>
                  <li><%= link_to "Sign in", new_user_session_path %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li data-no-turbolink><%= link_to "Card Manager", cards_path  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>